services:
  - type: web
    name: aapdasetu
    env: docker
    dockerFilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: ENV
        value: prod
      - key: LOG_LEVEL
        value: INFO
      - key: HOST
        value: 0.0.0.0
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: WEB3_PROVIDER_URI
        sync: false
      - key: BACKEND_WALLET_PRIVATE_KEY
        sync: false
      - key: AAPDA_SETU_CONTRACT_ADDRESS
        sync: false
